version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - ryangwu82
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    groups:
      minor-production-deps:
        dependency-type: 'production'
        update-types:
          - minor
          - patch
      minor-developent-deps:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
    ignore:
      # node-fetch v3.x is an ECMAscript module which we can't currently use.
      # v2 is still being supported indefinitely.
      - dependency-name: node-fetch
        versions:
          - '>= 3'
      # @github/actions v6.0.0 dropped support for Node 16.x
      - dependency-name: @github/actions
        versions:
          - '>= 6'
