name: 'Heroku Review App Action'
description: 'Creates a new Heroku review app when invoked'
inputs:
  heroku_email:
    description: 'The email address for the Heroku user that generated the personal access token'
    required: true
  heroku_api_key:
    description: 'The personal access token to use to access the Heroku API'
    required: true
  pipeline_name:
    description: "The name of the Heroku pipeline where the app should be deployed"
    required: true
  config_template_app:
    description: "If present, config vars wil be copied from this app instead of from pipeline CI defaults"
    required: false
  github_token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  heroku_region:
    description: 'Region to deploy newly-created apps'
    default: us
  heroku_stack:
    description: 'Name or identifier of Heroku stack to deploy on.'
    # heroku-20 is the stack used by readmeio, so it's safe for us to use internally
    default: heroku-20
  heroku_team:
    description: 'Name of the team that will own the new Heroku app.'
    default: readme
  docker:
    description: "If \"true\", this will build a Docker image on CircleCI and ship it to Heroku, instead of building directly on Heroku."
    default: "false"
  circleci_api_token:
    description: "CircleCI API credentials to invoke a new pipeline and check its status. Required if docker is true."
    required: false
  node_env:
    description: 'NODE_ENV value to pass to CircleCI build pipeline'
    required: false
outputs:
  comment:
    description: "A comment which can be posted to the pull request after the action finishes."
runs:
  using: 'node16'
  main: 'dist/index.js'
