version: 2.1

parameters:
  NODE_IMAGE:
    type: string
    default: '16.14.2'

jobs:
  build:
    docker:
      - image: cimg/node:<< pipeline.parameters.NODE_IMAGE >>

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Installing dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Running linters
          command: npm run lint

      - run:
          name: Building with ncc
          command: npm run build

      - run:
          name: Running unit tests
          command: npm test
