version: 2.1

parameters:
  NODE_IMAGE:
    type: string
    default: '16.14.2'

jobs:
  build:
    docker:
      - image: cimg/node:<< pipeline.parameters.NODE_IMAGE >>

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Installing dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Running linters
          command: npm run lint

      - run:
          name: Building with ncc
          command: |
            mv dist/index.js dist/index.js.orig
            npm run build
            ORIGINAL_BUILD_CHECKSUM="$(cat dist/index.js.orig | md5sum)"
            NEW_BUILD_CHECKSUM="$(cat dist/index.js | md5sum)"
            if [ "${ORIGINAL_BUILD_CHECKSUM}" != "${NEW_BUILD_CHECKSUM}" ]; then
              echo "Warning: ncc build doesn't match what's checked into dist/index.js."
              echo "Did you forget to 'npm run build' on this branch?"
              exit 1
            fi

      - run:
          name: Running unit tests
          command: npm test
